export const ADD_QUESTIONS = 'ADD_QUESTIONS'

export const ADD_RESPONSE = 'ADD_RESPONSE'

export const CHECK_RESPONSES = 'CHECK_RESPONSES'

export const RESPONSES_RESET = 'RESPONSES_RESET'

export const VALID_QUESTION_RESET = 'VALID_QUESTION_RESET'

export const VALIDATE_RESPONSES = 'VALIDATE_RESPONSES'
